Update README.md
Otherwise, you get this:
```
$ cargo run                                         101   crate  
    Updating crates.io index
error: no matching package named `webkit2gtk-rs` found
location searched: registry `crates-io`
required by package `myex v0.1.0 (/run/media/volker/DATA/cloned/webkit2gtk-rs/myex)`
```